name: Coverage badge

on:
  push:
    branches:
      - 'main'

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Start MySQL
      run: sudo systemctl start mysql.service

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Install npm packages
      run: npm ci
    - name: Test bundle build
      run: npm run build

    - name: Create Database
      run: mysql -uroot -proot -e "CREATE DATABASE testing"

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_HOST: localhost
        DB_USERNAME: root
        DB_PASSWORD: root
        XDEBUG_MODE: coverage
      run: echo "COVERAGE=$(php artisan test --coverage | grep -o [0-9.]*[[:space:]]% | tail -1)" >> $GITHUB_ENV
    - name: Update the Badge
      run: |
        curl -X PUT https://registry.davidday.tw/api/registry/$registryId \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer $token" \
        -d "{\"data\": \"{\\\"schemaVersion\\\":1,\\\"label\\\":\\\"Test Coverage\\\",\\\"message\\\":\\\"$COVERAGE\\\",\\\"color\\\":\\\"orange\\\"}\"}"
      env:
        token: ${{ secrets.WRITE_TOKEN }}
        registryId: 6fc9fa40-a6a5-4d72-b82c-31dcfcf7c24f
